train:
  dataset: dataset_nasa.csv
  target: Hazardous
  batch_size: 1024
  epochs: 40
  lr: 3e-3
  random_state: 42

test:
  dataset: dataset_nasa.csv
  target: Hazardous
  batch_size: 1024
  epochs: 40
  lr: 3e-3
  random_state: 42
